/**
  * @file   xroad_node_types.h
  * @brief CAUTION: do not change this file - it is autogenerated.
  */

#pragma once

#include <common/xroad_common_types.h>
#include <common/xroad_string.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C"
{
#endif

typedef struct xroad_cursor_s xroad_cursor_t;

xroad_str_decl(xroad_path, 1024u);

typedef uint64_t xroad_object_id_t;

typedef uint16_t xroad_node_id_t;

xroad_str_decl(xroad_node_name, 16u);

xroad_str_decl(xroad_config_name, 16u);

xroad_str_decl(xroad_group_name, 32u);

xroad_str_decl(xroad_system_name, 32u);

xroad_str_decl(xroad_link_name, 64u);

#ifdef __cplusplus
}
#endif
